### ISSUE TITLE
Can not access to assignments page.

### ISSUE THREAD

**Issue by elites-minami** [education/classroom#677]
We are going to use the "classroom for GitHub" (https://classroom.github.com/classrooms)  in order to manage all students up to 500 people and their assignments. 
After creation of classroom(New Classroom), I could not access to classroom page like "https://classroom.github.com/classrooms/xxxxxxxx-github-classroom"  with error message "We're sorry, but something went wrong. If you are the application owner check the logs for more information.". I can not access to any logs too.

Is this behavior correct? 

I could access Public repository of Assignments page like "https://classroom.github.com/classrooms/xxxxxxx-github-classroom/assignments/public".
 and "New Assignments" page like "https://classroom.github.com/classrooms/xxxxxx-github-classroom/new-assignment" directly.

How should I avoid/solve this critical problem to use classroom? 

Regards,
//minami

**Comment by tarebyte** [comment]
@elites-minami apologies for the issue, I'll look into this tomorrow.

**Comment by tarebyte** [comment]
@elites-minami looking at your assignments. There is one that includes all non english characters and unfortunately there is a known bug around this.

https://github.com/education/classroom/issues/266

**Comment by elites-minami** [comment]
Oops, we have two assignments.
One is, as you mentioned , including non english characters in the Title of assignment, however, another is not including non english characters. And both of them are not working right now...

**Comment by elites-minami** [comment]
I change my settings of Title from "non english characters" to "only english characters".
But there is no changes when I accessed my assignment page like "https://classroom.github.com/classrooms/XXXXX-my-first-github-classroom-experience".
Hmm, Ruby and RoR usually accept non english character by its nature, because Ruby is born in Japan, non english character environment :-P. What is the cause of this issue?

**Comment by tarebyte** [comment]
@elites-minami the Classroom app can accept non english characters. The problem is the GitHub API.

When creating a repo we currently don't accept characters that aren't part of the english keyboard.

So under the hood what we do is take the assignment name you give us and call [`name.parameterize`](https://github.com/education/classroom/blob/master/app/models/concerns/sluggable.rb#L12).

This is where the problem is.

**Comment by tarebyte** [comment]
Fixed by #728

**Comment by anilmndl** [comment]
I think this is still an issue. When I try to access the assignment page, I get 500 error.

https://classroom.github.com/classrooms/xxxx-xxx/assignments/example-assignment
